version: '3.9'
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend/src:/app/src
      - /app/node_modules
    environment:
      - PORT=4000
      - CORS_ORIGIN=http://localhost:5173
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:4000
    depends_on:
      - backend
