version: "3.9"
services:
  redis:
    image: redis:7-alpine
    container_name: oj_redis
    ports: ["6379:6379"]

  api:
    build: ./api
    container_name: oj_api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports: ["8000:8000"]
    volumes:
      - ./problems:/problems:rw
    depends_on: [redis]

  worker:
    build: ./worker
    container_name: oj_worker
    env_file:
      - .env.judge
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JOB_TMP_ROOT=/worker_tmp
      - HOST_JOB_TMP_ROOT=${PWD}/worker_tmp
      - PROBLEMS_ROOT=/problems
      - HOST_PROBLEMS_ROOT=${PWD}/problems
      - RUNS_PER_TEST=${RUNS_PER_TEST:-3}
      - PERFORMANCE_TOLERANCE=${PERFORMANCE_TOLERANCE:-0.10}
    volumes:
      - ./problems:/problems:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./worker_tmp:/worker_tmp
    depends_on: [redis]

  web:
    build: ./web
    container_name: oj_web
    ports: ["5173:5173"]   # web UI dev server
    depends_on: [api]
